### ISSUE TITLE
mpi_inf_3dhp_dataset.py

### ISSUE THREAD

**Issue by HQXing-11** [zemingxie/MPI_INF_3DHP-on-VideoPose3D#1]
Hello! I am interested in your work! When I run the file ‘prepare_data_mpi_inf_3dhp.py’，I find it lacks the file 'mpi_inf_3dhp_dataset.py'. Could you provide it? I am looking forward to your reply very much.

**Comment by zemingxie** [comment]
That is a little embarrassing. I forgot to upload it. It should be in there now.

**Comment by HQXing-11** [comment]
Thank you very much!
