### ISSUE TITLE
Simple questions about dataset

### ISSUE THREAD

**Issue by AIceDog** [zemingxie/MPI_INF_3DHP-on-VideoPose3D#2]
Hi, I am new to VideoPose3D and plan to train with mpi-inf-3dhp.

I wonder do I need the raw videos under mpi-inf-3dhp/train/S1/.....  to train model? 

Or I just need the data_2d_mpi_inf_3dhp_gt.npz and data_3d_mpi_inf_3dhp.npz produced by prepare_data_mpi_inf_3dhp.py to train model?

Thanks.

**Comment by zemingxie** [comment]
You do not need the videos to train the model.  VideoPose3D is trained on the 2D pose sequences only. The raw videos are needed because they need to overlay the poses onto the original video rather than doing any training with the original video.

**Comment by AIceDog** [comment]
I get it, thanks!
